# -*- coding: utf-8 -*-
import scrapy


class LouisvilleordinancesSpider(scrapy.Spider):
    name = "LouisvilleOrdinances"
    allowed_domains = ["http://library.amlegal.com/nxt/gateway.dll/Kentucky/"]
    start_urls = (
"Kentucky/loukymetro/titleigeneralprovisions/chapter10generalprovisions"
,"Kentucky/loukymetro/titleigeneralprovisions/chapter20administrativecode"
,"Kentucky/loukymetro/titleigeneralprovisions/chapter21ethicscode"
,"Kentucky/loukymetro/titleigeneralprovisions/chapter22recordsmanagement"
,"Kentucky/loukymetro/titleiiiadministration/chapter30executivedepartmentandofficeofi"
,"Kentucky/loukymetro/titleiiiadministration/chapter31reserved"
,"Kentucky/loukymetro/titleiiiadministration/chapter32administrativebodies"
,"Kentucky/loukymetro/titleiiiadministration/chapter33elections"
,"Kentucky/loukymetro/titleiiiadministration/chapter34meritboardforemployeesofcertain"
,"Kentucky/loukymetro/titleiiiadministration/chapter35personnelpolicies"
,"Kentucky/loukymetro/titleiiiadministration/chapter36policeandfiredepartmentsauxilia"
,"Kentucky/loukymetro/titleiiiadministration/chapter37procurementprocedures"
,"Kentucky/loukymetro/titleiiiadministration/chapter38taxation"
,"Kentucky/loukymetro/titleiiiadministration/chapter39metrogovernmentpolicies"
,"Kentucky/loukymetro/titleiiiadministration/chapter40funds"
,"Kentucky/loukymetro/titleiiiadministration/chapter41weapons"
,"Kentucky/loukymetro/titleiiiadministration/chapter42metro-ownedproperties"
,"Kentucky/loukymetro/titleiiiadministration/chapter43cemeteries"
,"Kentucky/loukymetro/titlevpublicworks/chapter50sewers"
,"Kentucky/loukymetro/titlevpublicworks/chapter51solidwaste"
,"Kentucky/loukymetro/titlevpublicworks/chapter52water"
,"Kentucky/loukymetro/titlevpublicworks/chapter53publicservicecorporations"
,"Kentucky/loukymetro/titleviitrafficcode/chapter70generalprovisions"
,"Kentucky/loukymetro/titleviitrafficcode/chapter71trafficrules"
,"Kentucky/loukymetro/titleviitrafficcode/chapter72parkingregulations"
,"Kentucky/loukymetro/titleviitrafficcode/chapter73equipmentandloads"
,"Kentucky/loukymetro/titleviitrafficcode/chapter74bicyclesandmotorcycles"
,"Kentucky/loukymetro/titleviitrafficcode/chapter75drivewaypermits"
,"Kentucky/loukymetro/titleviitrafficcode/chapter76trafficschedules"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter90smokefreelaw"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter91animals"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter92discriminatorypracticesfairhous"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter93emergencyservicetelephonecommun"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter94fireprevention"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter95hazardousmaterials"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter96healthregulationsandnuisances"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter97streetsandsidewalks"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter98boatregulations"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter99noise"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter100paradesandpublicassemblies"
,"Kentucky/loukymetro/titleixgeneralregulations/chapter101unsolicitedwrittenmaterials"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter110occupationallicensetax"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter111adultentertainmentestablishmen"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter112prohibitedbusinesspractices"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter113alcoholicbeverages"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter114automotiverecyclingdealersandj"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter115regulationsgoverningspecificbu"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter116communicationandcabletelevisio"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter117charitablesolicitations"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter118foodserviceestablishments"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter119reserved"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter120hazardouswastefacilities"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter121hotelsmotelsandsimilarbusiness"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter122insurancecompanies"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter123pawnbrokers"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter124armedsecurityofficers"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter125escortbureaus"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter126temporarysaleordisplayofmotorv"
,"Kentucky/loukymetro/titlexibusinessregulations/chapter127burglaryandhold-upalarmsystems"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter130generalprovisions"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter131offensesagainstproperty"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter132offensesagainstpublicpeace"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter133offensesagainstmorals"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter134offensesagainstpersons"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter135weaponscontrol"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter136reserved"
,"Kentucky/loukymetro/titlexiiigeneraloffenses/chapter137juvenileoffenses"
,"Kentucky/loukymetro/titlexvlandusage/chapter150buildingregulations"
,"Kentucky/loukymetro/titlexvlandusage/chapter151landlordandtenantcode"
,"Kentucky/loukymetro/titlexvlandusage/chapter152movingstructures"
,"Kentucky/loukymetro/titlexvlandusage/chapter153planning"
,"Kentucky/loukymetro/titlexvlandusage/chapter154propertyassessmentandreassessm"
,"Kentucky/loukymetro/titlexvlandusage/chapter155signs"
,"Kentucky/loukymetro/titlexvlandusage/chapter156propertymaintenancecode"
,"Kentucky/loukymetro/titlexvlandusage/chapter157floodplainmanagementordinance"
,"Kentucky/loukymetro/titlexvlandusage/chapter158louisvillejeffersoncountyenvir"
,"Kentucky/loukymetro/titlexvlandusage/chapter159erosionpreventionandsedimentco"
,"Kentucky/loukymetro/titlexvlandusage/chapter160downtownmanagementdistrict"
,"Kentucky/loukymetro/titlexvlandusage/chapter161neighborhooddevelopmentplans"
,"Kentucky/loukymetro/titlexvlandusage/chapter162overlaydistricts"
,"Kentucky/loukymetro/titlexvlandusage/chapter163developmentareas"
,"Kentucky/loukymetro/titlexvlandusage/chapter164systemdevelopmentchargesforroa"
)

    def parse(self, response):
        pass

